WI #86 #317 Improve support of SYMBOLIC CHARACTERS
TypeCobolTeam/TypeCobol pull request #1822
Opened 2020-12-11 16:58 UTC by fm-117

Fixes #317

Improve support for SYMBOLIC CHARACTERS (issue #86), parser now recognizes _symbolic-character-reference_ in different contexts.

2020-12-22 10:07 UTC, rooksdo requested changes

2020-12-22 10:07 UTC, rooksdo commented on TypeCobol.Test/Parser/Programs/Cobol85/SpecialNamesParagraph.rdz.cbl
> +       END PROGRAM TCOMFL06.
I suggest the following code sample to test that `SYMBOLIC CHARACTERS` is well supported (provided the execution output)
```cob
      
       IDENTIFICATION DIVISION.
       PROGRAM-ID. TCOMFL06.
       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       special-names.
           decimal-point comma
           SYMBOLIC CHARACTERS LOW-VAL IS 1
                               HEX-15  IS 22
                               HI-VAL  IS 256
           CLASS NAMECHAR IS 'A' THRU 'I'
                             'J' THRU 'R'
                             'S' THRU 'Z'
           .
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 var1 PIC X(10).
       01 var2 PIC X(10).
       01 var3 PIC X(10).
       01 c    PIC X.
       PROCEDURE DIVISION.
      *   Test NAMECHAR
           MOVE 'M'      TO c
           IF c IS NAMECHAR
              DISPLAY "TEST NAMECHAR OK"
           ELSE
              DISPLAY "TEST NAMECHAR FAILED"
           END-IF
      *   Test LOW-VAL
           MOVE 1        TO var1
           IF var1 EQUAL LOW-VAL
              DISPLAY "TEST LOW-VAL OK"
           ELSE
              DISPLAY "TEST LOW-VAL FAILED"
           END-IF
      *   Test HEX-15
           MOVE 22       TO var2
           IF var2 EQUAL HEX-15
              DISPLAY "TEST HEX-15 OK"
           ELSE
              DISPLAY "TEST HEX-15 FAILED"
           END-IF
      *   Test HI-VAL
           MOVE 256      TO var3
           IF var3 EQUAL HI-VAL
              DISPLAY "TEST HI-VAL OK"
           ELSE
              DISPLAY "TEST HI-VAL FAILED"
           END-IF
           GOBACK
           .
```

2020-12-22 13:13 UTC, fm-117 commented on TypeCobol.Test/Parser/Programs/Cobol85/SpecialNamesParagraph.rdz.cbl
> +           COPY CopyUsingSpecialNames.
The idea of the test is to check that the symbolic characters defined in the program are recognized also when they are  used in a COPY.

2020-12-22 13:21 UTC, rooksdo approved these changes

2020-12-22 13:21 UTC, rooksdo commented on TypeCobol.Test/Parser/Programs/Cobol85/SpecialNamesParagraph.rdz.cbl
> +           COPY CopyUsingSpecialNames.
OK

2020-12-22 13:21 UTC, rooksdo commented on TypeCobol.Test/Parser/Programs/Cobol85/CopyUsingSpecialNames.cpy
> +              DISPLAY "ok"
No sense.

2021-03-08 07:21 UTC, smedilol approved these changes

2021-03-10 08:30 UTC, mayanje approved these changes

2021-03-10 09:45 UTC, merged