WI #1825 Find and load analyzers from external assemblies
TypeCobolTeam/TypeCobol pull request #1826
Opened 2020-12-17 16:47 UTC by fm-117

Fixes #1825.
No error handling yet but it works...

2020-12-18 16:12 UTC, smedilol commented
As you say "No error handling yet", shall we validate or do you itendent to complete this PR ?

2020-12-21 10:01 UTC, fm-117 commented
In fact any error happening during the load of external analyzer will be caught by the default error handling mechanism:
- CLI will be interrupted, message and stacktrace will be reported
- LanguageServer will report the exception as usual unhandled exception
So I think it is ok to leave as it is.

2020-12-21 14:34 UTC, smedilol approved these changes

2020-12-21 14:40 UTC, rooksdo requested changes
All seems good to me but I wonder, is it possible to have an example of usage in this PR?

2020-12-22 14:35 UTC, rooksdo approved these changes

2020-12-22 15:03 UTC, merged