WI #1851 Update Perfs Test source code.
TypeCobolTeam/TypeCobol pull request #1859
Opened 2021-01-14 07:55 UTC by mayanje

Some test source code must have been changed a little bit: removing SYNC keyword, changing empty GROUP items.

2021-01-15 06:57 UTC, rooksdo commented on TypeCobol.Test/ThirdParty/CNAF_TypeCobol/CGMV01-DeepTypes.tcbl
> +               15 LT-MAX-CTYPER-PACKWK    PIC S9(9) COMP-5      VALUE 2.CGPACKWK
Why remove `SYNC` attribute ?

2021-01-15 08:00 UTC, fm-117 requested changes

2021-01-15 08:03 UTC, mayanje commented on TypeCobol.Test/ThirdParty/CNAF_TypeCobol/CGMV01-DeepTypes.tcbl
> +               15 LT-MAX-CTYPER-PACKWK    PIC S9(9) COMP-5      VALUE 2.CGPACKWK
It produces many semantic errors.

2021-01-15 08:05 UTC, mayanje commented on TypeCobol.Test/Parser/Performance/Performance.cs
> +﻿#define IGNORE_PERFS_TESTS
The fact is that there's on test which is not ignored.

2021-01-15 09:46 UTC, smedilol approved these changes

2021-01-15 10:54 UTC, fm-117 commented on TypeCobol.Test/Parser/Performance/Performance.cs
> +﻿#define IGNORE_PERFS_TESTS
But with this source, they will all run. Before your modification, perf tests were all ignored but one and know they are all active. Is that what we want ?

2021-01-15 10:58 UTC, mayanje commented on TypeCobol.Test/Parser/Performance/Performance.cs
> +﻿#define IGNORE_PERFS_TESTS
[TestMethod]
        [TestCategory("Performance")]
        [TestProperty("Time", "fast")]
        public void AntlrPerformanceProfiler()
were not ignored, so I just want confirmation by @smedilol then we can do what you suggest.

2021-01-15 11:32 UTC, rooksdo commented on TypeCobol.Test/ThirdParty/CNAF_TypeCobol/CGMV01-DeepTypes.tcbl
> +               15 LT-MAX-CTYPER-PACKWK    PIC S9(9) COMP-5      VALUE 2.CGPACKWK
Ok.

2021-01-15 12:06 UTC, rooksdo submitted a review, later dismissed

2021-01-15 12:49 UTC, smedilol commented on TypeCobol.Test/Parser/Performance/Performance.cs
> +﻿#define IGNORE_PERFS_TESTS
We can ignore the whole class if it's easier to manage.
Otherwise the solution with `#define` is fine for me.

2021-01-15 13:29 UTC, mayanje commented on TypeCobol.Test/Parser/Performance/Performance.cs
> +﻿#define IGNORE_PERFS_TESTS
All [Ignore] are commented except the one of the main class: 2b3aea

2021-01-15 13:36 UTC, fm-117 approved these changes

2021-01-15 15:30 UTC, smedilol approved these changes

2021-01-19 10:46 UTC, rooksdo approved these changes

2021-01-19 14:19 UTC, merged