1941 do not use tc qualifier for pure cobol completion
TypeCobolTeam/TypeCobol pull request #1957
Opened 2021-05-04 14:46 UTC by fm-117

Fixes #1941 

Minimal modification to the completion code to avoid '::' qualifier in variable completion suggestions. Does not affect procedures or variables from types that are always considered in a TypeCobol context.

2021-05-07 08:40 UTC, rooksdo approved these changes

2021-05-07 13:05 UTC, delevoye requested changes

2021-05-07 13:09 UTC, fm-117 commented on TypeCobol.LanguageServer/Completion Factory/CompletionFactory.cs
> +                    case TokenType.IN:
Yes, both can be used to separate parts of a qualified name.

2021-05-07 13:11 UTC, fm-117 commented on TypeCobol.LanguageServer/Completion Factory/CompletionFactory.cs
>          public static IEnumerable<CompletionItem> GetCompletionForTo(FileCompiler fileCompiler, CodeElement codeElement, Token userFilterToken, Token lastSignificantToken)
Well, there are many improvements to make in those 2 files, but this PR is not meant to be a full refactoring of the completion mechanism. But I agree this part of LanguageServer needs a bit of code clean-up...

2021-05-07 13:31 UTC, delevoye commented on TypeCobol.LanguageServer/Completion Factory/CompletionFactory.cs
>          public static IEnumerable<CompletionItem> GetCompletionForTo(FileCompiler fileCompiler, CodeElement codeElement, Token userFilterToken, Token lastSignificantToken)
Ok, looks like something to do in the future

2021-05-07 13:44 UTC, fm-117 commented on TypeCobol.LanguageServer/Completion Factory/CompletionFactory.cs
>          public static Node GetMatchingNode(FileCompiler fileCompiler, CodeElement codeElement)
Kept the private ones in the main class, moved `GetMatchingNode`. See 48a294cca394f4a4ca362ecb198e5f3c23160d1d.

2021-05-10 07:09 UTC, delevoye approved these changes

2021-05-12 12:00 UTC, mayanje approved these changes

2021-05-14 06:39 UTC, merged