WI #400 Check subscripts
TypeCobolTeam/TypeCobol pull request #2004
Opened 2021-07-15 15:34 UTC by fm-117

Partial fix for #400
- does not support TC typed data
- depends on #2001 for correct subscript parsing in function argument lists

2021-07-16 08:00 UTC, delevoye requested changes

2021-07-16 12:22 UTC, fm-117 commented on TypeCobol.Test/Parser/Programs/Cobol85/Subscripts.rdz.cbl
> +           MOVE item of tab1 (1 2)        TO elt
Yes, the idea was to have one case of 'not enough subscripts' and one case of 'too many subscript' on both one-dimensional and multi-dimensional arrays

2021-07-16 12:27 UTC, fm-117 commented on TypeCobol.Test/Parser/Programs/Cobol85/Subscripts.rdz.cbl
> +           MOVE item OF tab2 (1, 2, 3)    TO elt
Done in 1e805650d46fdd13eae2a428661fe54be9cfab00.

2021-07-16 13:41 UTC, delevoye approved these changes

2021-07-20 07:17 UTC, mayanje approved these changes

2021-07-29 13:36 UTC, rooksdo approved these changes

2021-07-29 15:22 UTC, merged