WI #2005 Convert ClassCondition.DataItem to ConditionalOperand
TypeCobolTeam/TypeCobol pull request #2006
Opened 2021-07-16 08:08 UTC by delevoye

Fix #2005

2021-07-16 12:14 UTC, fm-117 requested changes

2021-07-16 12:14 UTC, fm-117 commented on TypeCobol/Compiler/Parser/CodeElementBuilder/CobolExpressionsBuilder.cs
> +                Debug.Assert(classCondition.DataItem.Variable?.StorageArea != null); // This is how we created it above
It's not a new `Debug.Assert` but instead the condition must be updated. In fact you should factorize the storage area creation outside of the main `if`. From there you'll have a variable to test in order to update the dictionary. Easier.

2021-07-20 07:24 UTC, mayanje approved these changes

2021-07-20 07:27 UTC, fm-117 approved these changes

2021-07-29 06:42 UTC, merged