WI #2075 Use an empty SpaceSeparator token if empty replace.
TypeCobolTeam/TypeCobol pull request #2080
Opened 2021-11-17 16:17 UTC by mayanje

**What have been done**

This issue is in relation with #258, then case when the replacement token is null and both part to be replaced and the partial word are the same were missing, because in such sitution the resulting token is an empty token.
So the fix was to create an empty SpaceSeparator token.

A new test is added.

2021-11-18 11:57 UTC, fm-117 approved these changes

2021-11-22 12:56 UTC, smedilol requested changes

2021-11-22 12:56 UTC, smedilol commented on TypeCobol.Test/Parser/Preprocessor/ReplaceTestFiles/PgmEmptyPartialWordReplace2.cpy
> +﻿001390*REPLACE ==:-MAJ:== BY ==-TRACE==.                                01340000
Can you also create a test with a full program under "TypeCobol.Test/Parser/Programs/Cobol85/" just to be sure this PR integrates well with the rest ?

2021-11-25 08:44 UTC, fm-117 approved these changes

2021-11-25 11:35 UTC, smedilol approved these changes

2021-12-06 09:38 UTC, merged