WI #2069 Add check for condition names, and special check for level 88 data definitions.
TypeCobolTeam/TypeCobol pull request #2115
Opened 2022-01-20 15:31 UTC by mayanje

2022-01-21 08:29 UTC, fm-117 requested changes

2022-01-21 08:29 UTC, fm-117 commented on TypeCobol/Compiler/Diagnostics/CrossChecker.cs
> +                            if (usedKey.CodeElement?.LevelNumber.Value == 88 &&
Missing a null check on `LevelNumber`

2022-01-21 11:04 UTC, mayanje commented on TypeCobol/Compiler/Diagnostics/CrossChecker.cs
> +                            if (usedKey.CodeElement?.LevelNumber.Value == 88 &&
Changed in 08ade28

2022-01-21 11:05 UTC, mayanje commented on TypeCobol/Compiler/Diagnostics/CrossChecker.cs
> +                bool checkDataOrConditionStorageArea(DataOrConditionStorageArea dataOrConditionStorageArea)
Changed in 08ade28

2022-01-21 11:09 UTC, fm-117 approved these changes

2022-01-25 13:20 UTC, smedilol approved these changes

2022-02-16 13:52 UTC, merged