2087 allow when clause without instruction and forbid multiple when
TypeCobolTeam/TypeCobol pull request #2148
Opened 2022-02-22 13:23 UTC by laabidiHend

Fixes #2087 #2088

2022-02-23 08:22 UTC, fm-117 requested changes
This PR fails at build because of the 2 tests taht we attempted to correct. @laabidiHend, please restore the diagnostics in WhenTest.rdzMix.txt and WhenTestNoendEvaluate.rdzMix.txt. Also don't forget to update your branch with develop.

2022-02-23 08:22 UTC, fm-117 commented on TypeCobol/Compiler/CupParser/TypeCobolProgram.cup
> +        whenSearchCondition
indent

2022-02-23 08:22 UTC, fm-117 commented on TypeCobol/Compiler/Diagnostics/CrossChecker.cs
> +                DiagnosticUtils.AddError(whenSearch, "Missing statement in when clause",messageCode);
Missing space after second ','

2022-02-24 13:46 UTC, laabidiHend commented on TypeCobol/Compiler/Diagnostics/CrossChecker.cs
> +                DiagnosticUtils.AddError(whenSearch, "Missing statement in when clause",messageCode);
Fixes  ffc24a263c66ce8beb0feeb493fb5572060ccf59 2e092eb2943043ef771dbc24b9789b818a240caf

2022-02-24 14:54 UTC, smedilol requested changes

2022-02-28 09:38 UTC, laabidiHend commented on TypeCobol/Compiler/Diagnostics/CrossChecker.cs
> +                    }
i did the changes requested 2ca312a4dba3b9cd39cdcb14a394992afbbd1f32

2022-02-28 09:39 UTC, laabidiHend commented on TypeCobol/Compiler/Diagnostics/CrossChecker.cs
> +                    list.Add(whenSearch);
Done 2ca312a4dba3b9cd39cdcb14a394992afbbd1f32

2022-02-28 11:34 UTC, fm-117 approved these changes

2022-02-28 16:03 UTC, smedilol submitted a review, later dismissed

2022-03-08 12:11 UTC, mayanje approved these changes

2022-03-10 10:16 UTC, fm-117 approved these changes

2022-03-10 10:17 UTC, merged