2137 select star syntax
TypeCobolTeam/TypeCobol pull request #2164
Opened 2022-03-11 10:12 UTC by laabidiHend

#2137 Fixes

2022-03-11 16:01 UTC, fm-117 requested changes

2022-03-14 09:19 UTC, fm-117 commented on TypeCobol/Compiler/Sql/Model/FullSelect.cs
> +    public class FullSelect : SqlObject
See https://www.ibm.com/docs/en/db2-for-zos/12?topic=queries-fullselect, fullselect supports all the options of a SELECT operation and most importantly allows to combine multiple subselects using set operators (UNION, EXCEPT, INTERSECT)

2022-03-14 12:33 UTC, fm-117 requested changes

2022-03-14 12:33 UTC, fm-117 commented on TypeCobol/Compiler/Sql/CodeElements/SqlCodeElementBuilder.cs
> +using TypeCobol.Compiler.Sql.Nodes;
Yes I've checked with ReSharper, you should remove:

```csharp
using TypeCobol.Compiler.Parser;
using TypeCobol.Compiler.Scanner;
using TypeCobol.Compiler.Sql.Nodes;
```

2022-03-14 12:33 UTC, fm-117 commented on TypeCobol/Compiler/Sql/CodeElements/Statements/SelectStatement.cs
> +using TypeCobol.Compiler.Sql.Model;
Checked myself, everything can be removed except `using TypeCobol.Compiler.CodeElements;` and `using TypeCobol.Compiler.Sql.Model;`

2022-03-14 12:33 UTC, fm-117 commented on TypeCobol/Compiler/Sql/Nodes/Select.cs
> +{ /// <summary>
Indent is wrong, summary block should start on its own line

2022-03-18 08:54 UTC, fm-117 approved these changes
Ok for me unless we decide to improve the Token capture mechanism.

2022-03-21 07:10 UTC, smedilol requested changes

2022-03-21 07:10 UTC, smedilol commented on TypeCobol.Test/Parser/Programs/Cobol85/ExecSql/ExecSqlWithSelectStar.rdzMix.txt
> +Line 3[8,21] <27, Error, Syntax> - Syntax error : extraneous input 'DATADIVISION.' expecting {ExecStatementText, ExecStatementEnd, CommitStatement, SelectStatement}
Error on `data division` ?

2022-03-21 07:10 UTC, smedilol commented on TypeCobol/Compiler/Sql/Model/SelectClause.cs
> +        public override SelectionType Type => SelectionType.Star;
I don't know what is the best solution.
We need to discuss about `ConsumedTokens` and also properties like `SymbolInformationForTokens`, `StorageAreaDefinitions`, `StorageAreaReads` ...

2022-03-21 10:10 UTC, mayanje approved these changes

2022-03-21 15:07 UTC, smedilol approved these changes

2022-03-21 16:09 UTC, merged