WI #2196 Integrate lockTableStatement
TypeCobolTeam/TypeCobol pull request #2242
Opened 2022-05-27 09:34 UTC by laabidiHend

#2196 Fixes

2022-05-27 09:40 UTC, laabidiHend commented
I changed :
        private static bool IsSqlKeywordPart(char c)
        {
            return c == '-' || char.IsLetterOrDigit(c);
        }
Because tableName which is userDefinedWord in sql can contain digits and i think that also the all userDefinedWord they can contain letters and digits .

Also in the test i put a wrong statement (without MODE) to verifie that the error message exists .

2022-05-30 07:18 UTC, fm-117 requested changes

2022-05-30 07:18 UTC, fm-117 commented on TypeCobol.Test/Utils/Comparator.cs
> +                _writer.WriteLine($"line{lockTableStatement.Line}: {nameof(lockTableStatement)}");
Please add a space between 'line' and the actual number, correct the nameof expression. We want the name of the type not the parameter. Check other methods as a guide.

2022-05-30 07:18 UTC, fm-117 commented on TypeCobol/AntlrGrammar/CobolCodeElements.g4
> +sql_mode: ({ string.Equals(CurrentToken.Text, "MODE", System.StringComparison.OrdinalIgnoreCase) }? KeywordMODE=UserDefinedWord);
Is 'mode' already defined in grammar ? If the name is available I'd rather have a `mode` rule instead of `sql_mode`.

2022-05-30 07:18 UTC, fm-117 commented on TypeCobol/Compiler/Parser/CodeElementBuilder/CobolCodeElementBuilder.cs
> +	}
Indent problem

2022-05-30 07:18 UTC, fm-117 commented on TypeCobol/Compiler/Sql/CodeElements/Statements/LockTableStatement.cs
> +                                                     && astVisitor.SqlVisitor.ContinueVisit(PartitionId,Table);
spacing

2022-05-30 07:18 UTC, fm-117 commented on TypeCobol/Compiler/Sql/CodeElements/Statements/LockTableStatement.cs
> +        public SyntaxProperty<bool> IsPartitionInteger { get; }
I don't understand this property. The absence of partition id is already visible when `PartitionId` is null. Compared to `IsImmediate` in `TruncateStatement` for example, this is different. In TRUNCATE statement, the keyword IMMEDIATE changes the behavior of the statement so we capture this info using a `SyntaxProperty<bool>`. Here the relevant information is the partition identifier (including its absence) and this is fully captured through the `PartitionId` property.
Please remove the `IsPartitionInteger` property and adapt code accordingly.

2022-05-31 07:51 UTC, fm-117 commented on TypeCobol/Compiler/Sql/Model/SqlExpression.cs
> +            DumpProperty(output, nameof(Literal.LiteralValue), Literal.LiteralValue, indentLevel);
Ok this means that for SqlConstant, we only output the literal value. It's incomplete (no info on the token positioning for example) but it's fine.

2022-05-31 07:52 UTC, fm-117 approved these changes

2022-06-09 08:09 UTC, smedilol approved these changes

2022-06-10 07:22 UTC, merged