2246 integrate whenever statement
TypeCobolTeam/TypeCobol pull request #2255
Opened 2022-06-08 15:16 UTC by laabidiHend

Fixes #2246

2022-06-09 08:02 UTC, smedilol commented on TypeCobol/Compiler/Sql/CodeElements/Statements/WhenEverStatement.cs
> +        public SymbolReference HostLabel { get; }
After discussion : no, there is no need.
See grammar of Expression: https://www.ibm.com/docs/en/db2-for-zos/12?topic=elements-expressions

2022-06-09 08:06 UTC, fm-117 commented on TypeCobol/Compiler/Sql/CodeElements/Statements/WhenEverStatement.cs
> +        public SymbolReference HostLabel { get; }
HostLabel does not qualify as an expression in SQL, I think this is specific to this statement and not reusable in other contexts.

2022-06-09 08:29 UTC, fm-117 requested changes

2022-06-09 08:29 UTC, fm-117 commented on TypeCobol.Test/Parser/Programs/Cobol85/ExecSql/ExecSqlWithWhenEverStatement.rdzSQL.txt
> +- HostLabel = ENDDATA
I wanted name changes, see [my remark](https://github.com/TypeCobolTeam/TypeCobol/issues/2246#issuecomment-1148476563) in issue.

2022-06-09 08:29 UTC, fm-117 commented on TypeCobol/Compiler/Parser/CodeElementBuilder/CobolCodeElementBuilder.cs
> +	}
indent (but this file uses mixed indent so i know it's complicated to catch all errrors at first sight)

2022-06-09 08:29 UTC, fm-117 commented on TypeCobol/Compiler/Sql/CodeElements/Statements/WhenEverStatement.cs
> +        Sqlwarning
SqlError, SqlWarning

2022-06-09 14:41 UTC, laabidiHend commented on TypeCobol/Compiler/Sql/CodeElements/SqlCodeElementBuilder.cs
> +                            new AlphanumericValue(context.sqlGotoHostLabel().hostLabel as Token),
This will cause an error " context.sqlGotoHostLabel().hostLabel" is an IToken and not IParserTree node.

2022-06-13 07:33 UTC, fm-117 requested changes

2022-06-13 07:33 UTC, fm-117 commented on TypeCobol.Test/Utils/Comparator.cs
> +                DumpObject(nameof(whenEverStatement.TargetSectionOrParagraph), whenEverStatement.TargetSectionOrParagraph);
Now that i read it, could you merge the 2 methods `DumpObject`  and `DumpSqlObject` into a single one ?

2022-06-13 07:33 UTC, fm-117 commented on TypeCobol/Compiler/CodeElements/StatementElement.cs
> +        WhenEverStatement
After the merge, the order is not the same in both enums `CodeElementType`  and `StatementType`. While it's not important, I'd like to have the same order to simplify reading. Could you change that please ?

2022-06-13 07:33 UTC, fm-117 commented on TypeCobol/Compiler/Sql/CodeElements/SqlCodeElementBuilder.cs
> +                            new AlphanumericValue(context.sqlGotoHostLabel().hostLabel as Token),
Replace with direct cast.

2022-06-13 13:36 UTC, fm-117 requested changes

2022-06-13 13:36 UTC, fm-117 commented on TypeCobol.Test/Utils/Comparator.cs
> +            private void DumpObject(string name, SqlObject sqlObject, object @object)
No. I had something in mind similar to `DumpProperty`.

```csharp
private void DumpProperty(string name, object value)
{
    _writer.Write($"- {name} = ");
    if (value == null)
    {
        _writer.WriteLine("<NULL>");
    }
    else if (value is SqlObject sqlObject)
    {
        sqlObject.Dump(_writer, 1);
    }
    else
    {
        _writer.WriteLine(value.ToString());
    }
}
```

2022-06-16 09:35 UTC, fm-117 approved these changes

2022-06-16 09:37 UTC, merged