WI #2245 Integrate ReleaseSavepoint Statement
TypeCobolTeam/TypeCobol pull request #2263
Opened 2022-06-15 10:05 UTC by laabidiHend

Fixes #2245

2022-06-16 09:54 UTC, fm-117 requested changes

2022-06-16 09:54 UTC, fm-117 commented on TypeCobol.Test/Parser/Programs/Cobol85/ExecSql/ExecSqlWithReleaseSavepointStatement.rdz.cbl
> +              RELEASE SAVEPOINT
Please add variation using the optional TO keyword

2022-06-16 09:54 UTC, fm-117 commented on TypeCobol/Compiler/Parser/CodeElementBuilder/CobolCodeElementBuilder.cs
> +	}
indent

2022-06-16 09:54 UTC, fm-117 commented on TypeCobol/Compiler/Sql/CodeElements/SqlCodeElementBuilder.cs
> +            var savepointName=new SymbolReference((new AlphanumericValue((Token)context.savepoint_name)), SymbolType.SqlIdentifier);
spacing

2022-06-16 09:54 UTC, fm-117 commented on TypeCobol/Compiler/Sql/CodeElements/SqlCodeElementBuilder.cs
> +            if (context.savepoint_name == null) return null;
No. Like other statements, the builder should create them even if they are invalid/incomplete.

2022-06-16 09:54 UTC, fm-117 commented on TypeCobol/Compiler/Sql/CodeElements/Statements/ReleaseSavepointStatement.cs
> +	public class ReleaseSavepointStatement : SqlStatementElement
indent

2022-06-17 08:44 UTC, fm-117 requested changes

2022-06-17 08:44 UTC, fm-117 commented on TypeCobol.Test/Parser/Programs/Cobol85/ExecSql/ExecSqlWithReleaseSavepointStatement.rdzSQL.txt
> +- SavepointName = <missing UserDefinedWord>
Should be null, I think we'll have to check for diagnostics again

2022-06-21 08:46 UTC, fm-117 approved these changes

2022-07-04 09:12 UTC, smedilol approved these changes

2022-07-05 07:17 UTC, merged