WI #2313 Check tokens line length overflow when applying EI suffixing
TypeCobolTeam/TypeCobol pull request #2328
Opened 2022-08-23 15:54 UTC by fm-117

Fixes #2313.

2022-09-06 13:51 UTC, smedilol requested changes

2022-09-12 09:12 UTC, fm-117 commented on TypeCobol/Compiler/Directives/CompilerDirective.cs
> +        /// List of errors found when processing this CompilerDirective
done

2022-09-12 09:12 UTC, fm-117 commented on TypeCobol/Compiler/Directives/CompilerDirective.cs
> +        /// List of errors found when parsing this CompilerDirective
done

2022-09-13 11:02 UTC, smedilol approved these changes

2022-09-14 06:40 UTC, merged