WI #1860 Add semantic support for environment mnemonics
TypeCobolTeam/TypeCobol pull request #2369
Opened 2022-10-28 11:58 UTC by fm-117

Fixes #1860

2022-11-23 12:56 UTC, smedilol requested changes

2022-11-24 10:29 UTC, fm-117 commented on TypeCobol/Compiler/Diagnostics/CrossChecker.cs
> +            if (dataDefinition.SymbolTable.IsEnvironmentMnemonicNameDefined(dataDefinition.Name))
done

2022-11-24 10:30 UTC, fm-117 commented on TypeCobol/Compiler/CodeModel/SymbolTable.cs
> +        private SymbolTable GetRootGlobalTable()
I've renamed the first method as suggested. However the second one has already 23  usages, it existed prior to this PR.

2022-11-24 10:30 UTC, fm-117 commented on TypeCobol/Compiler/CodeModel/SymbolTable.cs
> +        private static void Add<T>([NotNull] IDictionary<string, List<T>> table, [NotNull] T symbol, [NotNull] Func<T, string> getName)
ok

2022-11-24 10:30 UTC, fm-117 commented on TypeCobol/Compiler/Parser/CodeElementBuilder/CobolCodeElementBuilder.cs
> +						// Duplicate mnemonic, add tu duplicate list and skip definition
done

2022-11-24 10:31 UTC, fm-117 commented on TypeCobol/Compiler/Diagnostics/CrossChecker.cs
> +                }
yes it's shorter and still clear

2022-11-24 10:32 UTC, fm-117 commented
I have to add some test cases for the visibility of mnemonics in case of nested pgms.
More commits to come...

2022-11-28 11:37 UTC, fm-117 commented on TypeCobol.Test/Parser/Programs/Cobol85/MnemonicsForEnvironment_Nested3.rdzPGM.txt
> +Line 57[8,31] <27, Error, Syntax> - Syntax error : The name 'SYSIN-M' was used for an item that was not defined as a data-name. References to this name may be resolved incorrectly.
Message updated

2022-11-28 12:37 UTC, smedilol approved these changes

2022-11-28 16:06 UTC, merged