2235 Optimize code element parser step in incremental
TypeCobolTeam/TypeCobol pull request #2370
Opened 2022-10-31 08:34 UTC by smedilol

Optimize code element parser step in incremental mode only.
In incremental mode, tokenIterator will now start at a more appropriate line to avoid iteration over all tokens of the document.

What's left to do:
- Specific incremental tests. We already have some incremental tests. I need to be sure that they cover the case of this implementation.
I've tested in our private IDE and it works fine so far.
- Create a performance test with a lot of COPY to reflect our real use case. 
   - One test with a modification in the data division
   - One test with a modification in the procedure division

Performance gain:
[Gain-2235.xlsx](https://github.com/TypeCobolTeam/TypeCobol/files/9899396/Gain-2235.xlsx)
As always with performance gain, if you run the same test twice, you won't gain exactly the same results. You can still see that CodeElementParserStep is close to 0ms.

2022-10-31 09:41 UTC, fm-117 requested changes

2022-10-31 09:41 UTC, fm-117 commented on TypeCobol/Compiler/Parser/CodeElementsParserStep.cs
> +                //Take previous line has long as there are tokens continued on this line
as long as

2022-10-31 09:41 UTC, fm-117 commented on TypeCobol/Compiler/Preprocessor/CopyTokensLinesIterator.cs
> +        public void Reset(int startLine = 0)
The method can be private and no need for a default value

2022-10-31 09:41 UTC, fm-117 commented on TypeCobol/Compiler/Preprocessor/CopyTokensLinesIterator.cs
> +        public CopyTokensLinesIterator(string sourceFileName, IReadOnlyList<IProcessedTokensLine> tokensLines, int channelFilter, int startLine = 0)
Used only once so better remove the default value

2023-02-06 10:22 UTC, smedilol commented
Replaced by #2433

2023-02-06 10:22 UTC, closed without merging