WI #2403 Move conversion of TextDocumentContentChangeEvents into TextChanges code to parser
TypeCobolTeam/TypeCobol pull request #2407
Opened 2022-12-21 13:48 UTC by fm-117

Fixes #2403

2023-01-06 07:54 UTC, smedilol requested changes

2023-01-06 07:54 UTC, smedilol commented on TypeCobol/Compiler/CompilationDocument.cs
> +                    // Remove all the old lines
I think we should try to merge the removal and insertion of lines in order to use `TextChangeType.LineUpdated`.
The goal is to optimize by limiting the update of LineIndex of all lines after the insertion of removal.

2023-01-06 08:34 UTC, fm-117 commented on TypeCobol.Test/Parser/Incremental/TextLineChanges/DeleteMultipleLines.inc
> +(8, 26) -> (14, 26)
I don't understand. For this edit the client will send on single RangeUpdate that corresponds to the area selected by user to remove. Do you mean creating a test with multiple RangeUpdate like one for each line ? Or the remark is for another test ?

2023-01-06 10:13 UTC, smedilol commented on TypeCobol/Compiler/CompilationDocument.cs
> +                    // Remove all the old lines
I've created issue #2416 for that.

2023-01-06 14:48 UTC, fm-117 commented on TypeCobol.Test/Parser/Incremental/TextLineChanges/DeleteMultipleLines.inc
> +(8, 26) -> (14, 26)
Added the test corresponding to multiple line deletion, each one on a single RangeUpdate

2023-01-11 10:06 UTC, smedilol approved these changes

2023-01-12 08:45 UTC, merged