WI #2416 Optimize text update by using line update mechanim when possible
TypeCobolTeam/TypeCobol pull request #2423
Opened 2023-01-24 16:07 UTC by fm-117

Fixes #2416.

This is incomplete as one LSR test fails in the current state of the branch.

2023-02-06 11:45 UTC, smedilol requested changes

2023-02-06 11:45 UTC, smedilol commented on TypeCobol/Compiler/CompilationDocument.cs
> +                                    : string.Empty;
Optional:
```suggestion
                                string newLine = lineUpdates?.Count > 0 ? lineUpdates[i] : string.Empty;
```

2023-02-06 11:45 UTC, smedilol commented on TypeCobol/Compiler/CompilationDocument.cs
>                              : 1;
Optional:
```suggestion
                        int lineUpdatesCount = lineUpdates?.Count > 0 ? lineUpdates.Count : 1;
```

2023-02-06 11:45 UTC, smedilol commented on TypeCobol/Compiler/CompilationDocument.cs
> +                }
No need to iterate over all lines if there is nothing more to do
```suggestion
                    if (offset == 0 && encounteredCodeElement)
                        break; //Nothing more to do
                }
```

2023-02-06 12:53 UTC, smedilol commented
Here's a proposal for others changes in `CompilationDocument`. 
See this diff :
[CompilationDocumentProposal.txt](https://github.com/TypeCobolTeam/TypeCobol/files/10663156/CompilationDocumentProposal.txt)

2023-02-06 16:09 UTC, fm-117 commented on TypeCobol/Compiler/CompilationDocument.cs
> +                                    : string.Empty;
done

2023-02-06 16:09 UTC, fm-117 commented on TypeCobol/Compiler/CompilationDocument.cs
>                              : 1;
done

2023-02-07 07:14 UTC, smedilol approved these changes

2023-02-07 08:59 UTC, merged