WI #2427 Reset line's PreprocessorState before line update
TypeCobolTeam/TypeCobol pull request #2428
Opened 2023-01-30 14:37 UTC by fm-117

Fixes #2427 !

2023-02-07 07:15 UTC, smedilol requested changes

2023-02-07 09:32 UTC, fm-117 commented on TypeCobol.Test/Parser/Incremental/AdvancedEdits/EditMultilineCompilerDirectiveRemoveLine.rdz.cbl
> +       IDENTIFICATION DIVISION.
done but not reviewed yet

2023-02-07 09:32 UTC, fm-117 commented on TypeCobol.Test/Parser/Incremental/AdvancedEdits/EditMultilineCompilerDirectiveAddLine.rdz.cbl
> +       IDENTIFICATION DIVISION.
done but not reviewed yet

2023-02-13 07:29 UTC, smedilol approved these changes

2023-02-13 07:51 UTC, merged