WI #1673 Fix continuation group scanning in incremental mode
TypeCobolTeam/TypeCobol pull request #2445
Opened 2023-02-14 09:44 UTC by fm-117

Fixes #1673.

The solution used here will likely be updated when working on #2364 and its children.

2023-02-14 16:20 UTC, smedilol requested changes

2023-02-15 08:40 UTC, fm-117 commented on TypeCobol/Compiler/Scanner/ScannerStep.cs
>                              }
This won't work as we do not have ScanState yet for all lines participating in the group.
We can use the `scanState` provided to the method but it won't work for special case involving REPLACE directives. The infamous combo : REPLACE + CONTINUATION + DEBUG + INCREMENTAL !

2023-02-15 08:59 UTC, fm-117 commented on TypeCobol/Compiler/Scanner/ScannerStep.cs
>                              }
Also why not add the line no matter their type in the group ? I mean not scanning Invalid / Blank / Comment is ok but the scanner will handle them correctly anyway and we have to re-scan MultiFormalizedComment so isn't it better to add the lines without checking their type ?

2023-02-15 09:16 UTC, fm-117 commented on TypeCobol/Compiler/Scanner/ScannerStep.cs
>                              }
Proposal:
[patch.txt](https://github.com/TypeCobolTeam/TypeCobol/files/10741342/patch.txt)

2023-02-15 13:33 UTC, smedilol commented on TypeCobol/Compiler/Scanner/ScannerStep.cs
>                              }
As discussed together, ok to keep the code as first proposed in your PR.
We will eventually handle a mix of Debug line and continuation line in #2446.

2023-02-20 08:10 UTC, smedilol approved these changes

2023-02-20 08:23 UTC, merged