WI #2444 Defer diagnostic reset during incremental parsing
TypeCobolTeam/TypeCobol pull request #2458
Opened 2023-02-21 15:30 UTC by fm-117

Fixes #2444.

2023-02-23 08:50 UTC, smedilol requested changes
Can you create a dedicated incremental test in order to understand what was not working before this PR ?

2023-02-23 10:38 UTC, fm-117 commented
> Can you create a dedicated incremental test in order to understand what was not working before this PR ?

@smedilol It's done. 2 tests were failing the "add empty line at beginning then remove" change, I've reproduced them in a shorter form in the new test files.

2023-02-27 10:23 UTC, smedilol approved these changes

2023-02-27 12:21 UTC, merged

2023-02-28 13:11 UTC, fm-117 commented
Some explanations for the new unit tests:

### CEAlteringScanState
#### Before the fix
The diagnostic `Error in copy 'DataDivision' at line 1 : Syntax error : Syntax not supported: 'DATA DIVISION' has been found inside COPY.` would disappear after adding an empty line at the beginning. The other 2 diagnostics would remain and be correctly shifted down.
#### After the fix
All 3 diagnostics are there and move up or down correctly, according to the lines added or removed

### MissingSpaceAfterProgId
#### Before the fix
The diagnostic `A blank was missing before character "P" in column 19. A blank was assumed.` would disappear after adding an empty line at the beginning.
#### After the fix
The diagnostic is there after each step (after initial parsing, after adding line, after removing line)