2489 exit paragraph section
TypeCobolTeam/TypeCobol pull request #2500
Opened 2023-04-17 16:14 UTC by efr15

Fixes #2489

2023-04-18 06:37 UTC, fm-117 requested changes

2023-04-18 06:37 UTC, fm-117 commented on TypeCobol.Test/Parser/Programs/Cobol85/Exit.PGM.txt
Use a Node or CodeElement formatter instead because here the PGM formatter only reveals that the parser does not produce any error on this sample.

2023-04-18 06:37 UTC, fm-117 commented on TypeCobol/Compiler/Parser/CodeElementBuilder/CobolCodeElementBuilder.cs
> +		public override void EnterAllocateStatement(CodeElementsParser.AllocateStatementContext context)
indent (but it's ok to keep it like that)

2023-04-18 11:50 UTC, efr15 commented on TypeCobol.Test/Parser/Programs/Cobol85/Exit.PGM.txt
Done. Nodes and CodeElements are indeed more meaningful with this sample.

2023-04-18 12:38 UTC, fm-117 approved these changes

2023-04-18 13:54 UTC, fm-117 approved these changes

2023-04-19 06:46 UTC, smedilol approved these changes

2023-04-19 07:11 UTC, merged