WI #2319 Allow missing sentence ending in grammar, check later
TypeCobolTeam/TypeCobol pull request #2510
Opened 2023-05-02 09:04 UTC by fm-117

Fixes #2319 but we'll keep the fixing and logging code in `ProgramClassBuilder` for a while. So keep the issue open also.

2023-05-02 10:01 UTC, smedilol requested changes
Can you also add the test from the issue ?

2023-05-02 12:05 UTC, smedilol submitted a review, later dismissed

2023-05-03 08:53 UTC, efr15 requested changes

2023-05-03 09:02 UTC, fm-117 commented on TypeCobol/Compiler/Nodes/Node.cs
> +            int myIndex = Parent.IndexOf(this);
Incredible optimization ! I buy it.

2023-05-03 09:06 UTC, smedilol submitted a review, later dismissed

2023-05-03 09:07 UTC, efr15 approved these changes

2023-05-03 09:51 UTC, merged