WI #2538 Split EI-Legacy REPLACING syntax option over 2 separate options
TypeCobolTeam/TypeCobol pull request #2551
Opened 2023-07-07 08:59 UTC by fm-117

Fixes #2538

2023-07-07 13:19 UTC, efr15 requested changes

2023-07-07 13:20 UTC, efr15 submitted a review, later dismissed

2023-07-07 13:20 UTC, fm-117 commented on TypeCobol/Compiler/Directives/TypeCobolOptions.cs
> +        public bool EILegacy_ApplyCopySuffixing { get; set; } = true;
Yep it definitely should...

2023-07-18 07:34 UTC, efr15 submitted a review, later dismissed

2023-07-24 08:25 UTC, efr15 approved these changes

2023-07-28 10:24 UTC, smedilol approved these changes

2023-07-28 10:27 UTC, merged