WI #2218 Preserve column and line while rescanning during a REPLACE
TypeCobolTeam/TypeCobol pull request #2570
Opened 2023-08-30 13:10 UTC by smedilol

WI #2218 Scan during Replace preserve original column and line

Temporary Virtual Line used to rescan replaced token:
- Always use the lineIndex of the original line
- The line preserve space characters before first token
- Keep the ColumnLayout of the original line

Rewrite AutoReplaceIterator with AbstractReplaceTokensLinesIterator.

2023-09-01 14:49 UTC, efr15 submitted a review, later dismissed

2023-09-05 14:23 UTC, fm-117 requested changes
no test ?

2023-09-05 14:23 UTC, fm-117 commented on TypeCobol/Compiler/Preprocessor/AutoReplacePartialWordsTokensDocument.cs
> +                    var replacementToken = new Token(TokenType.UserDefinedWord, nextToken.StartIndex, tempTokensLine.Length - 1, tempTokensLine);
Why not keeping using `GenerateReplacementToken` ?

2023-09-08 16:23 UTC, fm-117 commented on TypeCobol/Compiler/Preprocessor/AutoReplacePartialWordsTokensDocument.cs
> +                    var replacementToken = new Token(TokenType.UserDefinedWord, nextToken.StartIndex, tempTokensLine.Length - 1, tempTokensLine);
Yeah ok I see it, no need to rescan as we already know the token type

2023-09-11 08:58 UTC, fm-117 approved these changes

2023-09-11 08:58 UTC, merged