WI #2674 Adapt unit test to run on Linux
TypeCobolTeam/TypeCobol pull request #2690
Opened 2024-12-30 09:44 UTC by fm-117

Ignore work item used in commits. Apparently it is not required to have a special process for `\r`, instead some adaptations have been done through the tests to make them run on Linux.

2025-01-03 14:53 UTC, efr15 requested changes
There are a lot of modifications in this PR including functional changes, technical improvements and so on. It's not easy to see all the impacts. Let's trust the automated tests...

2025-01-06 09:49 UTC, fm-117 commented on Codegen/src/Generators/LinearNodeSourceCodeMapper.cs
> +            /// - Node's Target Line Offsets.
Done

2025-01-06 09:54 UTC, fm-117 commented on TypeCobol.Analysis/Graph/CfgDotFileForNodeGenerator.cs
> +            _edgesBuffer ??= new StringWriter(writer.FormatProvider) { NewLine = writer.NewLine };
`_edgesBuffer` is shared with the parent generator, if any. The initialization is performed here only for root generator and then the instance is passed from parent to children. At the end of the full generation (for the whole `CompilationUnit`), both instances are set to `null`.

2025-01-06 09:58 UTC, fm-117 commented on TypeCobol.LanguageServer.Test/LSRTests/NoWindows_ExecuteCommandRefactorAdjustFillers/input/ExecuteCommandRefactorAdjustFillers.tlsp
> +      "message": "{\"jsonrpc\":\"2.0\",\"id\":\"1\",\"method\":\"workspace/applyEdit\",\"params\":{\"label\":\"Adjust FILLERs: 3 FILLER(s) modified\",\"edit\":{\"changes\":{\"file:/C:/Users/GDLRUSER/
See https://github.com/TypeCobolTeam/TypeCobol/blob/08e72ac02512c2c6f7c2850c9bdd340715dd830e/TypeCobol.LanguageServer.Test/LSRTest.cs#L565

Is it enough ?

2025-01-06 10:00 UTC, fm-117 commented on TypeCobol.Test/TestUtils.cs
> -            //Set to true to automatically replace content in ExpectedResult File
Apparently yes. Restored.

2025-01-06 11:12 UTC, fm-117 commented on TypeCobol.LanguageServer.Test/LSRTests/NoWindows_ExecuteCommandRefactorAdjustFillers/input/ExecuteCommandRefactorAdjustFillers.tlsp
> +      "message": "{\"jsonrpc\":\"2.0\",\"id\":\"1\",\"method\":\"workspace/applyEdit\",\"params\":{\"label\":\"Adjust FILLERs: 3 FILLER(s) modified\",\"edit\":{\"changes\":{\"file:/C:/Users/GDLRUSER/
See updated tests

2025-01-07 09:24 UTC, efr15 approved these changes

2025-01-07 09:50 UTC, merged